"""empty message

Revision ID: 036aa307db24
Revises: ed39584189ff
Create Date: 2020-03-26 16:29:06.801950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036aa307db24'
down_revision = 'ed39584189ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_created_on'), 'question', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_created_on'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
