"""empty message

Revision ID: 48aa4e59a485
Revises: 9f28eb8a5ab2
Create Date: 2020-04-09 14:01:23.005828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48aa4e59a485'
down_revision = '9f28eb8a5ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_created_on'), 'info', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_created_on'), table_name='info')
    op.drop_table('info')
    # ### end Alembic commands ###
